name: memcached-ci
on:
  push:
    branches: [ master ]
    
env:
  MEMCACHED_VERSION: "dummy" # Should be set from build/version file

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Read memcached version
        run: cat build/version >> $GITHUB_ENV 
  test:
    needs: [init]
    runs-on: ubuntu-latest
    container:
      image: amazonlinux:2022
    steps:
      - name: Install essentials
        run: |
          yum install -y \
            tar \
            gzip
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Check out memcached
        uses: actions/checkout@v2
        with:
          repository: memcached/memcached
          path: memcached
          ref: ${{ env.MEMCACHED_VERSION }}
      - name: Run test
        working-directory: ./memcached
        run: ../amazonlinux/test-memcached.sh

  build:
    needs: [init]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Check out memcached
        uses: actions/checkout@v2
        with:
          repository: memcached/memcached
          path: amazonlinux/memcached
          ref: ${{ env.MEMCACHED_VERSION }}
      - name: Build image
        working-directory: ./amazonlinux
        run: |
          docker build -t memcached:amazonlinux2 .
          docker images
