name: memcached-ci
on:
  push:
    branches: [ master ]

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      memcached-version: ${{ steps.memcached_version.outputs.version }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Read memcached version
        id: memcached_version
        run: |
          source build/version
          echo "::set-output name=version::${MEMCACHED_VERSION}"
  test:
    needs: [init]
    runs-on: ubuntu-latest
    container:
      image: amazonlinux:2022
    steps:
      - name: Install essentials
        run: |
          yum install -y \
            tar \
            gzip
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Check out memcached
        uses: actions/checkout@v2
        with:
          repository: memcached/memcached
          path: memcached
          ref: ${{ needs.init.outputs.memcached-version }}
      - name: Run test
        working-directory: ./memcached
        run: ../amazonlinux/test-memcached.sh

  build:
    needs: [init]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Check out memcached
        uses: actions/checkout@v2
        with:
          repository: memcached/memcached
          path: amazonlinux/memcached
          ref: ${{ needs.init.outputs.memcached-version }}
      - name: Build image
        working-directory: ./amazonlinux
        run: |
          docker build -t memcached:amazonlinux2 .
          docker images
